# Initial cache for the pre-populated Fedora source archive. No network at build time.
get_filename_component(_source "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
foreach(_dependency appimageupdate zsync2 libappimage args)
    string(TOUPPER "${_dependency}" _upper)
    if(NOT EXISTS "${_source}/vendor/${_dependency}/CMakeLists.txt")
        message(FATAL_ERROR "Missing ${_dependency}; run packaging/fedora/prepare-source.py first")
    endif()
    set(FETCHCONTENT_SOURCE_DIR_${_upper} "${_source}/vendor/${_dependency}" CACHE PATH "" FORCE)
endforeach()
set(FETCHCONTENT_FULLY_DISCONNECTED ON CACHE BOOL "" FORCE)
set(FETCHCONTENT_UPDATES_DISCONNECTED ON CACHE BOOL "" FORCE)
set(BUILD_LIBAPPIMAGEUPDATE_ONLY ON CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "Dependency tests require additional sources" FORCE)
set(USE_SYSTEM_CPR ON CACHE BOOL "Use Fedora CPR and curl" FORCE)
set(USE_SYSTEM_SQUASHFUSE ON CACHE BOOL "" FORCE)
set(CMAKE_BUILD_TYPE Release CACHE STRING "")
